//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inferis.KindjesNet.Blog.OldServices.Blog {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.inferis.org/baby/Backend", ConfigurationName="OldServices.Blog.BlogBackendSoap")]
    public interface BlogBackendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetLocalTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetLocalTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetAllBlogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetAllBlogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetArticlesByBlog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetArticlesByBlog(int blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetCommentsByBlog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetCommentsByBlog(int blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetCommentsByArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetCommentsByArticle(int articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetPostersByBlog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetPostersByBlog(int blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/GetArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetArticle(int articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/CreateArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int CreateArticle(int blogId, int posterId, string title, string body, System.DateTime stamp, System.DateTime lastmodified, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/UpdateArticle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateArticle(int articleId, int posterId, string title, string body, System.DateTime stamp, System.DateTime lastmodified, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.inferis.org/baby/Backend/RemoveComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void RemoveComment(int commentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface BlogBackendSoapChannel : Inferis.KindjesNet.Blog.OldServices.Blog.BlogBackendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BlogBackendSoapClient : System.ServiceModel.ClientBase<Inferis.KindjesNet.Blog.OldServices.Blog.BlogBackendSoap>, Inferis.KindjesNet.Blog.OldServices.Blog.BlogBackendSoap {
        
        public BlogBackendSoapClient() {
        }
        
        public BlogBackendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogBackendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogBackendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogBackendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLocalTime() {
            return base.Channel.GetLocalTime();
        }
        
        public System.Data.DataSet GetAllBlogs() {
            return base.Channel.GetAllBlogs();
        }
        
        public System.Data.DataSet GetArticlesByBlog(int blogId) {
            return base.Channel.GetArticlesByBlog(blogId);
        }
        
        public System.Data.DataSet GetCommentsByBlog(int blogId) {
            return base.Channel.GetCommentsByBlog(blogId);
        }
        
        public System.Data.DataSet GetCommentsByArticle(int articleId) {
            return base.Channel.GetCommentsByArticle(articleId);
        }
        
        public System.Data.DataSet GetPostersByBlog(int blogId) {
            return base.Channel.GetPostersByBlog(blogId);
        }
        
        public System.Data.DataSet GetArticle(int articleId) {
            return base.Channel.GetArticle(articleId);
        }
        
        public int CreateArticle(int blogId, int posterId, string title, string body, System.DateTime stamp, System.DateTime lastmodified, int status) {
            return base.Channel.CreateArticle(blogId, posterId, title, body, stamp, lastmodified, status);
        }
        
        public void UpdateArticle(int articleId, int posterId, string title, string body, System.DateTime stamp, System.DateTime lastmodified, int status) {
            base.Channel.UpdateArticle(articleId, posterId, title, body, stamp, lastmodified, status);
        }
        
        public void RemoveComment(int commentId) {
            base.Channel.RemoveComment(commentId);
        }
    }
}
